site_name: Luv documentation
site_url: http://luv.readthedocs.org
pages:
  - What is Luv?: index.md
  - Installation: install.md
  - Usage: usage.md
  - Luv API:
    - fs: uv_fs.md
markdown_extensions:
  - admonition
  - fenced_code
  - codehilite:
      noclasses: True
      pygments_style: colorful
  - toc:
      permalink: True
