site_name: Luv Docs - Unofficial
site_url: http://luv.readthedocs.org
repo_url: https://github.com/develephant/luv-docs
pages:
  - What is Luv?: index.md
  - Installation: install.md
  - Usage: usage.md
  - Luv API:
    - async: async/index.md
    - check: check/index.md
    - fs: fs/index.md
    - idle: idle/index.md
    - pipe: pipe/index.md
    - poll: poll/index.md
    - prepare: prepare/index.md
    - signal: signal/index.md
    - socket poll: socket_poll/index.md
    - tcp: tcp/index.md
    - thread: thread/index.md
    - timer: timer/index.md
    - tty: tty/index.md
    - udp: udp/index.md
    - work: work/index.md
markdown_extensions:
  - admonition
  - fenced_code
  - codehilite:
      noclasses: True
      pygments_style: colorful
  - toc:
      permalink: True
